runtime: php83

instance_class : F1

env_variables:
    GOOGLE_STORAGE_BUCKET: "epic-patient-lookup.appspot.com"
    CLOUDSQL_CONNECTION_NAME: "epic-patient-lookup:us-east1:epic-pt-lookup-mysql"
    CLOUDSQL_HOST: "35.227.92.19"
    CLOUDSQL_USER: "root"
    CLOUDSQL_PASSWORD: "passw0rd!"
    CLOUDSQL_DATABASE_NAME: "epic-pt-lookup-db"